### ISSUE TITLE
Discrepancy between doctr output and the docs

### ISSUE THREAD

**Issue by choldgraf** [drdoctr/doctr#205]
The doctr output says this:

`doctr deploy <deploy_directory>`

But the docs say this:

`doctr deploy . --built-docs path/to/built/html/`

Are these equivalent?

**Comment by asmeurer** [comment]
That's because we didn't do a release yet, and our docs are based on master. 

They are the same, but generally you will need the `--built-docs` flag (unless you use Sphinx, in which case it detects it automatically). The `<deploy directory>` is where ever you want the docs to go in gh-pages, but that's usually `.` so we just changed it to that.
