### ISSUE TITLE
fatal: 'doctr_remote/gh-pages' is not a commit

### ISSUE THREAD

**Issue by rabernat** [drdoctr/doctr#277]
I am trying use doctr to build and deploy an organization project page for a sphinx site

This is happening when doctr tries to deploy:
```
git fetch doctr_remote
Checking out doctr working branch tracking doctr_remote/gh-pages
git checkout -b __doctr_working_branch --track doctr_remote/gh-pages
fatal: 'doctr_remote/gh-pages' is not a commit and a branch '__doctr_working_branch' cannot be created from it
```

https://travis-ci.org/pangeo-data/pangeo#L747

I don't really understand the error message. Could the problem possibly be the fact that the `gh-pages` branch does not exist on this repo yet?

**Comment by asmeurer** [comment]
Hi, yes. This is a bug that should be fixed in master already. Since several people seem to be running into this, I guess I'll do a release. 

Note that the error should go away once you merge. It only occurs when gh-pages doesn't exist and it doesn't have permissions to create it (i.e., the build is a PR build).

**Comment by asmeurer** [comment]
OK, I've done a 1.6.3 release, which is out for pip installs now (the conda install will be out as soon as https://github.com/conda-forge/doctr-feedstock/pull/23 is merged). Let me know if you still see the error.

**Comment by rabernat** [comment]
Yes, I it looks like the 1.6.3 release has fixed my problem!

Thanks for this fantastic package.

**Comment by asmeurer** [comment]
Great. Let me know if you have any other issues or suggestions.
